# Generated by Django 5.2.17 on 2026-09-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0003_contas_alter_cadfeiras_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('saida', models.CharField(max_length=250, verbose_name='Saída')),
                ('parcela', models.CharField(max_length=100, verbose_name='Parcelas')),
                ('fornecedor', models.CharField(max_length=250, verbose_name='Fornecedor')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.contas', verbose_name='Forma de pagamento')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ('date',),
            },
        ),
    ]
