# Generated by Django 5.2.17 on 2026-08-31 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feiras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField(verbose_name='Quantidade')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('pagment', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro')], max_length=20, verbose_name='Forma de pagamento')),
                ('nomeFeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadfeiras', verbose_name='Feira')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Venda de feiras',
                'verbose_name_plural': 'Venda de Feiras',
                'ordering': ('nomeFeira',),
            },
        ),
        migrations.CreateModel(
            name='Precificacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('impressao', models.IntegerField(verbose_name='Hora de impressão')),
                ('filament', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Filamento')),
                ('embalagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Embalagem')),
                ('acessorios', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acessórios')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preço de custo')),
                ('sugerido', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='valor sugerido')),
                ('vanda', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Venda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.product', unique=True, verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Precificação',
                'verbose_name_plural': 'Precificação',
                'ordering': ('product',),
            },
        ),
    ]
