# Generated by Django 5.2.17 on 2026-09-01 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendasFeiras',
            fields=[
                ('feira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cadastro.cadfeiras', verbose_name='Feira')),
                ('total_debito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Débito')),
                ('total_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Crédito')),
                ('total_pix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PIX')),
                ('total_dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinheiro')),
                ('total_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Total de Vendas Feiras',
                'verbose_name_plural': 'Total de Vendas Feiras',
                'ordering': ('feira',),
            },
        ),
    ]
