# Generated by Django 5.2.17 on 2026-09-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cadclientes_alter_cadfeiras_options_and_more'),
        ('vendas', '0002_vendasfeiras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feiras',
            options={'ordering': ('nomeFeira', 'product'), 'verbose_name': 'Venda de feiras', 'verbose_name_plural': 'Venda de Feiras'},
        ),
        migrations.AlterField(
            model_name='feiras',
            name='pagment',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix')], max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.CreateModel(
            name='VendasInternas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('pagment', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix')], max_length=50, verbose_name='Formas de pagamento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadclientes', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.product', verbose_name='Produto')),
            ],
        ),
    ]
