# Generated by Django 5.2.17 on 2026-09-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_feiras_options_alter_feiras_pagment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feiras',
            options={'ordering': ('nomeFeira', 'id'), 'verbose_name': 'Venda de feiras', 'verbose_name_plural': 'Venda de Feiras'},
        ),
        migrations.AlterModelOptions(
            name='vendasfeiras',
            options={'ordering': ('-feira',), 'verbose_name': 'Total de Vendas Feiras', 'verbose_name_plural': 'Total de Vendas Feiras'},
        ),
        migrations.AlterModelOptions(
            name='vendasinternas',
            options={'ordering': ('-date', 'product'), 'verbose_name': 'Vendas Internas', 'verbose_name_plural': 'Vendas Internas'},
        ),
    ]
