# Generated by Django 5.2.17 on 2026-08-31 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadFeiras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Cadasro de feiras',
                'verbose_name_plural': 'Cadasro de feiras',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='FilamentBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Marca de filamento',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FilametType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de filamento',
            },
        ),
        migrations.CreateModel(
            name='Filment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Filamento')),
                ('color', models.CharField(max_length=100, verbose_name='Cor')),
                ('filamentBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.filamentbrand', verbose_name='Marca')),
                ('filamentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.filamettype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'FilamentoS',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('product', models.CharField(max_length=200, unique=True, verbose_name='Produto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produtos',
                'ordering': ('product',),
            },
        ),
    ]
