# Generated by Django 5.2.17 on 2026-09-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadClientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, unique=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cadastro de Cliente',
                'verbose_name_plural': 'Cadastro de clientes',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='cadfeiras',
            options={'ordering': ('name',), 'verbose_name': 'Cadasro de feiras', 'verbose_name_plural': 'Cadastro de feiras'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='filamentbrand',
            options={'ordering': ('name',), 'verbose_name': 'Marca de filamento', 'verbose_name_plural': 'Marcas de filamento'},
        ),
        migrations.AlterModelOptions(
            name='filamettype',
            options={'verbose_name': 'Tipo de filamento', 'verbose_name_plural': 'Tipos de filamento'},
        ),
        migrations.AlterModelOptions(
            name='filment',
            options={'verbose_name': 'FilamentoS', 'verbose_name_plural': 'Filamentos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product',), 'verbose_name': 'Produtos', 'verbose_name_plural': 'Produtos'},
        ),
    ]
