# Generated by Django 5.2.17 on 2026-09-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cadclientes_alter_cadfeiras_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=200, verbose_name='Cartão')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do titular')),
                ('operacao', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('PIX', 'PIX'), ('SAQUE', 'Saque')], max_length=50, verbose_name='Operação')),
                ('apelido', models.CharField(max_length=200, verbose_name='Nome do Cartão')),
            ],
            options={
                'verbose_name': 'Contas Bancarias',
                'verbose_name_plural': 'Contas Bancarias',
                'ordering': ('apelido',),
            },
        ),
        migrations.AlterModelOptions(
            name='cadfeiras',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'Cadasro de feiras', 'verbose_name_plural': 'Cadastro de feiras'},
        ),
    ]
